#!/bin/sh

	if [ "$1" = "--v" ]; then
		echo Log_1  : Version : planckdr 1.0
		exit 0
	elif [ "$1" = "--h" ]; then
		if [ -f "$WORK_ENV/help/planckdr.txt" ]; then
			cat $WORK_ENV/help/planckdr.txt
		else
			echo $WORK_ENV/help/planckdr.txt not found
		fi
		exit 0
	else
		echo Unexpected argument: + $1 +.  Aborting...
		exit 1
	fi

echo The component you have called + $0 + is a container for other
echo executables.  This one does nothing.  Exiting.
exit 0
